const exerciseLibrary = [
  {
    id: "chest-press",
    name: "Chest Press",
    muscle: "Chest",
    sets: 3,
    reps: 10,
    weight: 50,
    cue: "Keep your shoulder blades back and press smoothly.",
  },
  {
    id: "incline-press",
    name: "Incline Press",
    muscle: "Chest",
    sets: 3,
    reps: 10,
    weight: 35,
    cue: "Control the lowering phase and press through a steady path.",
  },
  {
    id: "cable-fly",
    name: "Cable Fly",
    muscle: "Chest",
    sets: 3,
    reps: 12,
    weight: 15,
    cue: "Use a controlled arc and squeeze your chest.",
  },
  {
    id: "shoulder-press",
    name: "Shoulder Press",
    muscle: "Shoulders",
    sets: 3,
    reps: 10,
    weight: 25,
    cue: "Keep your ribs down and avoid locking your elbows.",
  },
  {
    id: "lateral-raise",
    name: "Lateral Raise",
    muscle: "Shoulders",
    sets: 3,
    reps: 12,
    weight: 10,
    cue: "Raise to shoulder height without swinging.",
  },
  {
    id: "triceps-pushdown",
    name: "Triceps Pushdown",
    muscle: "Triceps",
    sets: 3,
    reps: 12,
    weight: 30,
    cue: "Keep your elbows pinned to your sides.",
  },
  {
    id: "lat-pulldown",
    name: "Lat Pulldown",
    muscle: "Back",
    sets: 3,
    reps: 10,
    weight: 55,
    cue: "Pull your elbows down and keep your chest tall.",
  },
  {
    id: "seated-row",
    name: "Seated Row",
    muscle: "Back",
    sets: 3,
    reps: 10,
    weight: 50,
    cue: "Pull toward your lower ribs and avoid shrugging.",
  },
  {
    id: "reverse-fly",
    name: "Reverse Fly",
    muscle: "Rear Delts",
    sets: 3,
    reps: 12,
    weight: 20,
    cue: "Move slowly and squeeze your shoulder blades together.",
  },
  {
    id: "biceps-curl",
    name: "Biceps Curl",
    muscle: "Biceps",
    sets: 3,
    reps: 12,
    weight: 20,
    cue: "Keep your elbows still and control each rep.",
  },
  {
    id: "hammer-curl",
    name: "Hammer Curl",
    muscle: "Biceps",
    sets: 3,
    reps: 12,
    weight: 15,
    cue: "Keep your wrists neutral and avoid swinging.",
  },
  {
    id: "leg-press",
    name: "Leg Press",
    muscle: "Legs",
    sets: 3,
    reps: 10,
    weight: 90,
    cue: "Keep your back against the pad and control the depth.",
  },
  {
    id: "leg-extension",
    name: "Leg Extension",
    muscle: "Quads",
    sets: 3,
    reps: 12,
    weight: 40,
    cue: "Lift smoothly and avoid snapping your knees straight.",
  },
  {
    id: "leg-curl",
    name: "Leg Curl",
    muscle: "Hamstrings",
    sets: 3,
    reps: 12,
    weight: 40,
    cue: "Keep your hips down and curl with control.",
  },
  {
    id: "calf-raise",
    name: "Calf Raise",
    muscle: "Calves",
    sets: 3,
    reps: 15,
    weight: 50,
    cue: "Pause at the top and lower through a full range.",
  },
  {
    id: "hip-abduction",
    name: "Hip Abduction",
    muscle: "Glutes",
    sets: 3,
    reps: 12,
    weight: 45,
    cue: "Stay controlled and avoid bouncing the weight.",
  },
  {
    id: "plank",
    name: "Plank",
    muscle: "Core",
    sets: 3,
    reps: 30,
    weight: 0,
    cue: "Keep your body in one straight line and brace your core.",
  },
  {
    id: "cable-crunch",
    name: "Cable Crunch",
    muscle: "Core",
    sets: 3,
    reps: 12,
    weight: 30,
    cue: "Move through your torso instead of pulling with your arms.",
  },
];
